### PR TITLE
fix: support custom crontab

### LINKED ISSUE #37: Support overwriting default crontab
## Current behaviour
When `/ark/config/crontab` does not exist, the `run.sh` will create a default crontab, trying to update the server and mods every 30min.

### Change
Add a `ConfigMap` containing a default crontab compatible with this Chart that can be overwritten through values.yaml.

### PR DESCRIPTION
**Pull request by DrPsychick**
closes #37

### CODE REVIEW

**Comment by ntrehout** [comment]
Hello ! Are you planning to merge this PR it would be nice ! :)

**Comment by DrPsychick** [comment]
Yes! Seems like I have forgotten this PR :)

**Comment by DrPsychick** [comment]
I currently have no easy way of testing it, could you test the changes @ntrehout  and report back if it works?

**Comment by ntrehout** [comment]
Sure I will let you know. :)

**Review by ntrehout — APPROVED** [review]
Helm lint works, i deployed it in a clean K3S cluster. All good on my side ! 🚀

**Pull request merged**
